version: 2
jobs:
  build:
    branches:
      ignore:
        - gh-pages
    docker:
      - image: circleci/node:8
    working_directory: ~/repo
    environment:
      - SRC_BRANCH: master
      - PAGES_BRANCH: gh-pages
      # Following variables should be added in the build settings page:
      # - GH_EMAIL
      # - GH_NAME
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: npm run test
      - run: npm run main:test:report
      - run: npm run main:test:coverage
      - store_artifacts:
          path: test/results/results.xml
          prefix: tests
      - store_artifacts:
          path: test/coverage
          prefix: coverage
      - store_test_results:
          path: test/results
          prefix: tests
      - deploy:
          command: |
            if [ $CIRCLE_BRANCH == $SRC_BRANCH ]; then
              git config --global user.email $GH_EMAIL
              git config --global user.name $GH_NAME
              git clone $CIRCLE_REPOSITORY_URL pages

              cd pages
              git checkout $PAGES_BRANCH || git checkout --orphan $PAGES_BRANCH
              git rm -rf .
              cd ..

              npm run build
              cp -a docs/. pages/.
              mkdir -p pages/.circleci && cp -a .circleci/. pages/.circleci/.

              cd pages
              git add -A
              git commit -m "Deploy to GitHub Pages (CircleCI: ${CIRCLE_SHA1})" --allow-empty
              git push origin $PAGES_BRANCH
            fi
